noun = input("Noun: ")
noun2 = input("Noun #2: ")
noun3 = input("Noun #3: ")
verb = input("Verb: ")
verb2 = input("Verb #2: ")
verb3 = input("Verb #3: ")
adjv = input("Adjective: ")
adjv2 = input("Adjective #2: ")
adjv3 = input("Adjective #3: ")
name = input("Name: ")
name2 = input("Name #2: ")
animal = input("Animal: ")
location = input("Location: ")
terrain = input("Terrain: ")

print(("\nOnce upon a time there lived a {} named {}. He was very {} because he was always {}. One day he was {} in the {} {} within {}, his home, when he was met with the daunting task of slaying {}, the {} {} but we all know that our hero is too much of a {} for that. Knowing this, he returns back home to his trusty {} to resume his adventure another day. The end! ").format(noun, name, adjv, verb, verb2, adjv2, terrain, location, name2, adjv3, animal, noun2, noun3))